---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: experts-backend
    labels:
        app: experts-backend
    namespace: stack-experts
spec:
    replicas: 1
    selector:
        matchLabels:
            app: experts-backend
    template:
        metadata:
            labels:
                app: experts-backend
        spec:
            containers:
                - name: experts
                  image: experts:latest
                  imagePullPolicy: Never
                  env:
                  - name: GOOGLE_APPLICATION_CREDENTIALS
                    valueFrom:
                      secretKeyRef:
                        name: experts-env-variables
                        key: appconfig
                  - name: AMPQ_URL
                    valueFrom:
                      secretKeyRef:
                        name: experts-env-variables
                        key: ampq
                  ports:
                     - containerPort: 8000