apiVersion: v1
kind: Service
metadata:
    namespace: stack-experts
    name: experts-service
    labels:
        app: experts-service
spec:
    type: NodePort
    ports:
    - port: 80
      protocol: TCP
    selector:
        app: experts-backend